const WORDS = [
  { id: 1, ru: "и", en: "and", cs: "a", tier: 1 },
  { id: 2, ru: "в", en: "in", cs: "v", tier: 1 },
  { id: 3, ru: "не", en: "not", cs: "ne", tier: 1 },
  { id: 4, ru: "он", en: "he", cs: "on", tier: 1 },
  { id: 5, ru: "на", en: "on, at", cs: "na", tier: 1 },
  { id: 6, ru: "я", en: "I", cs: "já", tier: 1 },
  { id: 7, ru: "что", en: "what, that", cs: "co, že", tier: 1 },
  { id: 8, ru: "с", en: "with", cs: "s", tier: 1 },
  { id: 9, ru: "а", en: "and, but", cs: "a, ale", tier: 1 },
  { id: 10, ru: "как", en: "how, like", cs: "jak", tier: 1 },
  { id: 11, ru: "но", en: "but", cs: "ale", tier: 1 },
  { id: 12, ru: "к", en: "to, toward", cs: "k", tier: 1 },
  { id: 13, ru: "э́то", en: "this", cs: "to", tier: 1 },
  { id: 14, ru: "по", en: "along, by", cs: "po", tier: 1 },
  { id: 15, ru: "она́", en: "she", cs: "ona", tier: 1 },
  { id: 16, ru: "мы", en: "we", cs: "my", tier: 1 },
  { id: 17, ru: "за", en: "behind, for", cs: "za", tier: 1 },
  { id: 18, ru: "о", en: "about", cs: "o", tier: 1 },
  { id: 19, ru: "от", en: "from", cs: "od", tier: 1 },
  { id: 20, ru: "все", en: "all, everyone", cs: "všichni", tier: 1 },
  { id: 21, ru: "так", en: "so, thus", cs: "tak", tier: 1 },
  { id: 22, ru: "у", en: "at, by", cs: "u", tier: 1 },
  { id: 23, ru: "вы", en: "you (plural)", cs: "vy", tier: 1 },
  { id: 24, ru: "то", en: "then, that", cs: "to", tier: 1 },
  { id: 25, ru: "из", en: "from, out of", cs: "z", tier: 1 },
  { id: 26, ru: "ещё", en: "still, yet", cs: "ještě", tier: 1 },
  { id: 27, ru: "до", en: "before, until", cs: "do", tier: 1 },
  { id: 28, ru: "бы", en: "would", cs: "by", tier: 1 },
  { id: 29, ru: "да", en: "yes", cs: "ano", tier: 1 },
  { id: 30, ru: "нет", en: "no", cs: "ne", tier: 1 },
  { id: 31, ru: "для", en: "for", cs: "pro", tier: 1 },
  { id: 32, ru: "себя́", en: "oneself", cs: "sebe", tier: 1 },
  { id: 33, ru: "вот", en: "here is", cs: "hle", tier: 1 },
  { id: 34, ru: "мой", en: "my", cs: "můj", tier: 1 },
  { id: 35, ru: "то́лько", en: "only", cs: "jen, pouze", tier: 1 },
  { id: 36, ru: "свой", en: "one's own", cs: "svůj", tier: 1 },
  { id: 37, ru: "кото́рый", en: "which, that", cs: "který", tier: 1 },
  { id: 38, ru: "тако́й", en: "such", cs: "takový", tier: 1 },
  { id: 39, ru: "друго́й", en: "other, another", cs: "jiný, další", tier: 1 },
  { id: 40, ru: "и́ли", en: "or", cs: "nebo", tier: 1 },
  { id: 41, ru: "е́сли", en: "if", cs: "jestli, pokud", tier: 1 },
  { id: 42, ru: "когда́", en: "when", cs: "když, kdy", tier: 1 },
  { id: 43, ru: "уже́", en: "already", cs: "už", tier: 1 },
  { id: 44, ru: "ну", en: "well", cs: "no", tier: 1 },
  { id: 45, ru: "ведь", en: "after all", cs: "vždyť", tier: 1 },
  { id: 46, ru: "то́же", en: "also, too", cs: "také", tier: 1 },
  { id: 47, ru: "да́же", en: "even", cs: "dokonce", tier: 1 },
  { id: 48, ru: "чем", en: "than", cs: "než", tier: 1 },
  { id: 49, ru: "ме́жду", en: "between", cs: "mezi", tier: 1 },
  { id: 50, ru: "раз", en: "once, time", cs: "jednou, krát", tier: 1 },
  { id: 51, ru: "мо́жет", en: "can, maybe", cs: "může, možná", tier: 1 },
  { id: 52, ru: "че́рез", en: "through, across", cs: "přes", tier: 1 },
  { id: 53, ru: "сейча́с", en: "now", cs: "teď", tier: 1 },
  { id: 54, ru: "наш", en: "our", cs: "náš", tier: 1 },
  { id: 55, ru: "тогда́", en: "then", cs: "tehdy, pak", tier: 1 },
  { id: 56, ru: "год", en: "year", cs: "rok", tier: 1 },
  { id: 57, ru: "де́ло", en: "matter, affair", cs: "věc, záležitost", tier: 1 },
  { id: 58, ru: "вре́мя", en: "time", cs: "čas", tier: 1 },
  { id: 59, ru: "день", en: "day", cs: "den", tier: 1 },
  { id: 60, ru: "рука́", en: "hand, arm", cs: "ruka", tier: 1 },
  { id: 61, ru: "жизнь", en: "life", cs: "život", tier: 1 },
  { id: 62, ru: "челове́к", en: "person, man", cs: "člověk", tier: 1 },
  { id: 63, ru: "сло́во", en: "word", cs: "slovo", tier: 1 },
  { id: 64, ru: "голова́", en: "head", cs: "hlava", tier: 1 },
  { id: 65, ru: "ме́сто", en: "place", cs: "místo", tier: 1 },
  { id: 66, ru: "дом", en: "house, home", cs: "dům", tier: 1 },
  { id: 67, ru: "глаз", en: "eye", cs: "oko", tier: 1 },
  { id: 68, ru: "ночь", en: "night", cs: "noc", tier: 1 },
  { id: 69, ru: "рабо́та", en: "work, job", cs: "práce", tier: 1 },
  { id: 70, ru: "вода́", en: "water", cs: "voda", tier: 1 },
  { id: 71, ru: "земля́", en: "earth, land", cs: "země", tier: 1 },
  { id: 72, ru: "лицо́", en: "face", cs: "tvář, obličej", tier: 1 },
  { id: 73, ru: "дверь", en: "door", cs: "dveře", tier: 1 },
  { id: 74, ru: "сторона́", en: "side", cs: "strana", tier: 1 },
  { id: 75, ru: "мир", en: "world, peace", cs: "svět, mír", tier: 1 },
  { id: 76, ru: "быть", en: "to be", cs: "být", tier: 1 },
  { id: 77, ru: "мочь", en: "can, to be able", cs: "moci, moct", tier: 1 },
  { id: 78, ru: "сказа́ть", en: "to say, tell", cs: "říct", tier: 1 },
  { id: 79, ru: "знать", en: "to know", cs: "znát, vědět", tier: 1 },
  { id: 80, ru: "стать", en: "to become", cs: "stát se", tier: 1 },
  { id: 81, ru: "говори́ть", en: "to speak, say", cs: "mluvit, říkat", tier: 1 },
  { id: 82, ru: "хоте́ть", en: "to want", cs: "chtít", tier: 1 },
  { id: 83, ru: "ду́мать", en: "to think", cs: "myslet", tier: 1 },
  { id: 84, ru: "ви́деть", en: "to see", cs: "vidět", tier: 1 },
  { id: 85, ru: "де́лать", en: "to do, make", cs: "dělat", tier: 1 },
  { id: 86, ru: "идти́", en: "to go (walk)", cs: "jít", tier: 1 },
  { id: 87, ru: "стоя́ть", en: "to stand", cs: "stát", tier: 1 },
  { id: 88, ru: "дать", en: "to give", cs: "dát", tier: 1 },
  { id: 89, ru: "жить", en: "to live", cs: "žít", tier: 1 },
  { id: 90, ru: "смотре́ть", en: "to look, watch", cs: "dívat se", tier: 1 },
  { id: 91, ru: "о́чень", en: "very", cs: "velmi, moc", tier: 1 },
  { id: 92, ru: "большо́й", en: "big, large", cs: "velký", tier: 1 },
  { id: 93, ru: "но́вый", en: "new", cs: "nový", tier: 1 },
  { id: 94, ru: "хорошо́", en: "well, good", cs: "dobře", tier: 1 },
  { id: 95, ru: "пе́рвый", en: "first", cs: "první", tier: 1 },
  { id: 96, ru: "здесь", en: "here", cs: "tady, zde", tier: 1 },
  { id: 97, ru: "там", en: "there", cs: "tam", tier: 1 },
  { id: 98, ru: "мно́го", en: "much, many", cs: "hodně, mnoho", tier: 1 },
  { id: 99, ru: "тут", en: "here", cs: "tady", tier: 1 },
  { id: 100, ru: "есть", en: "is, there is", cs: "je", tier: 1 },
  { id: 101, ru: "го́род", en: "city", cs: "město", tier: 2 },
  { id: 102, ru: "страна́", en: "country", cs: "země", tier: 2 },
  { id: 103, ru: "доро́га", en: "road", cs: "cesta", tier: 2 },
  { id: 104, ru: "шко́ла", en: "school", cs: "škola", tier: 2 },
  { id: 105, ru: "война́", en: "war", cs: "válka", tier: 2 },
  { id: 106, ru: "кни́га", en: "book", cs: "kniha", tier: 2 },
  { id: 107, ru: "у́тро", en: "morning", cs: "ráno", tier: 2 },
  { id: 108, ru: "ве́чер", en: "evening", cs: "večer", tier: 2 },
  { id: 109, ru: "друг", en: "friend", cs: "přítel", tier: 2 },
  { id: 110, ru: "оте́ц", en: "father", cs: "otec", tier: 2 },
  { id: 111, ru: "мать", en: "mother", cs: "matka", tier: 2 },
  { id: 112, ru: "же́нщина", en: "woman", cs: "žena", tier: 2 },
  { id: 113, ru: "ребёнок", en: "child", cs: "dítě", tier: 2 },
  { id: 114, ru: "окно́", en: "window", cs: "okno", tier: 2 },
  { id: 115, ru: "ко́мната", en: "room", cs: "pokoj", tier: 2 },
  { id: 116, ru: "маши́на", en: "car", cs: "auto", tier: 2 },
  { id: 117, ru: "де́ньги", en: "money", cs: "peníze", tier: 2 },
  { id: 118, ru: "вопро́с", en: "question", cs: "otázka", tier: 2 },
  { id: 119, ru: "исто́рия", en: "history, story", cs: "historie", tier: 2 },
  { id: 120, ru: "часть", en: "part", cs: "část", tier: 2 },
  { id: 121, ru: "систе́ма", en: "system", cs: "systém", tier: 2 },
  { id: 122, ru: "коне́ц", en: "end", cs: "konec", tier: 2 },
  { id: 123, ru: "нача́ло", en: "beginning", cs: "začátek", tier: 2 },
  { id: 124, ru: "слу́чай", en: "case, occasion", cs: "případ", tier: 2 },
  { id: 125, ru: "си́ла", en: "force, strength", cs: "síla", tier: 2 },
  { id: 126, ru: "мину́та", en: "minute", cs: "minuta", tier: 2 },
  { id: 127, ru: "час", en: "hour", cs: "hodina", tier: 2 },
  { id: 128, ru: "нога́", en: "leg, foot", cs: "noha", tier: 2 },
  { id: 129, ru: "стол", en: "table", cs: "stůl", tier: 2 },
  { id: 130, ru: "у́лица", en: "street", cs: "ulice", tier: 2 },
  { id: 131, ru: "и́мя", en: "name", cs: "jméno", tier: 2 },
  { id: 132, ru: "число́", en: "number", cs: "číslo", tier: 2 },
  { id: 133, ru: "путь", en: "way, path", cs: "cesta", tier: 2 },
  { id: 134, ru: "пра́вда", en: "truth", cs: "pravda", tier: 2 },
  { id: 135, ru: "де́вушка", en: "girl", cs: "dívka", tier: 2 },
  { id: 136, ru: "поня́ть", en: "to understand", cs: "pochopit", tier: 2 },
  { id: 137, ru: "взять", en: "to take", cs: "vzít", tier: 2 },
  { id: 138, ru: "прийти́", en: "to come", cs: "přijít", tier: 2 },
  { id: 139, ru: "найти́", en: "to find", cs: "najít", tier: 2 },
  { id: 140, ru: "писа́ть", en: "to write", cs: "psát", tier: 2 },
  { id: 141, ru: "спроси́ть", en: "to ask", cs: "zeptat se", tier: 2 },
  { id: 142, ru: "игра́ть", en: "to play", cs: "hrát", tier: 2 },
  { id: 143, ru: "рабо́тать", en: "to work", cs: "pracovat", tier: 2 },
  { id: 144, ru: "люби́ть", en: "to love", cs: "milovat", tier: 2 },
  { id: 145, ru: "чита́ть", en: "to read", cs: "číst", tier: 2 },
  { id: 146, ru: "помо́чь", en: "to help", cs: "pomoct", tier: 2 },
  { id: 147, ru: "нача́ть", en: "to begin", cs: "začít", tier: 2 },
  { id: 148, ru: "каза́ться", en: "to seem", cs: "zdát se", tier: 2 },
  { id: 149, ru: "оста́вить", en: "to leave", cs: "nechat", tier: 2 },
  { id: 150, ru: "вести́", en: "to lead", cs: "vést", tier: 2 },
  { id: 151, ru: "отве́тить", en: "to answer", cs: "odpovědět", tier: 2 },
  { id: 152, ru: "понима́ть", en: "to understand", cs: "rozumět", tier: 2 },
  { id: 153, ru: "бро́сить", en: "to throw", cs: "hodit", tier: 2 },
  { id: 154, ru: "пить", en: "to drink", cs: "pít", tier: 2 },
  { id: 155, ru: "сего́дня", en: "today", cs: "dnes", tier: 2 },
  { id: 156, ru: "стара́ться", en: "to try", cs: "snažit se", tier: 2 },
  { id: 157, ru: "получи́ть", en: "to receive", cs: "dostat", tier: 2 },
  { id: 158, ru: "лежа́ть", en: "to lie down", cs: "ležet", tier: 2 },
  { id: 159, ru: "сиде́ть", en: "to sit", cs: "sedět", tier: 2 },
  { id: 160, ru: "бежа́ть", en: "to run", cs: "běžet", tier: 2 },
  { id: 161, ru: "ходи́ть", en: "to walk, to go", cs: "chodit", tier: 2 },
  { id: 162, ru: "ста́рый", en: "old", cs: "starý", tier: 2 },
  { id: 163, ru: "ма́ленький", en: "small", cs: "malý", tier: 2 },
  { id: 164, ru: "молодо́й", en: "young", cs: "mladý", tier: 2 },
  { id: 165, ru: "ру́сский", en: "Russian", cs: "ruský", tier: 2 },
  { id: 166, ru: "после́дний", en: "last", cs: "poslední", tier: 2 },
  { id: 167, ru: "дли́нный", en: "long", cs: "dlouhý", tier: 2 },
  { id: 168, ru: "бе́лый", en: "white", cs: "bílý", tier: 2 },
  { id: 169, ru: "кра́сный", en: "red", cs: "červený", tier: 2 },
  { id: 170, ru: "чёрный", en: "black", cs: "černý", tier: 2 },
  { id: 171, ru: "высо́кий", en: "tall, high", cs: "vysoký", tier: 2 },
  { id: 172, ru: "гла́вный", en: "main", cs: "hlavní", tier: 2 },
  { id: 173, ru: "пото́м", en: "then, later", cs: "potom", tier: 2 },
  { id: 174, ru: "опя́ть", en: "again", cs: "zase", tier: 2 },
  { id: 175, ru: "всегда́", en: "always", cs: "vždy", tier: 2 },
  { id: 176, ru: "никогда́", en: "never", cs: "nikdy", tier: 2 },
  { id: 177, ru: "вме́сте", en: "together", cs: "spolu", tier: 2 },
  { id: 178, ru: "сно́ва", en: "again", cs: "znovu", tier: 2 },
  { id: 179, ru: "бы́стро", en: "quickly", cs: "rychle", tier: 2 },
  { id: 180, ru: "далеко́", en: "far", cs: "daleko", tier: 2 },
  { id: 181, ru: "совсе́м", en: "completely", cs: "úplně", tier: 2 },
  { id: 182, ru: "немно́го", en: "a little", cs: "trochu", tier: 2 },
  { id: 183, ru: "мужчи́на", en: "man", cs: "muž", tier: 2 },
  { id: 184, ru: "брат", en: "brother", cs: "bratr", tier: 2 },
  { id: 185, ru: "сестра́", en: "sister", cs: "sestra", tier: 2 },
  { id: 186, ru: "сын", en: "son", cs: "syn", tier: 2 },
  { id: 187, ru: "дочь", en: "daughter", cs: "dcera", tier: 2 },
  { id: 188, ru: "семья́", en: "family", cs: "rodina", tier: 2 },
  { id: 189, ru: "за́втра", en: "tomorrow", cs: "zítra", tier: 2 },
  { id: 190, ru: "вчера́", en: "yesterday", cs: "včera", tier: 2 },
  { id: 191, ru: "ка́ждый", en: "each, every", cs: "každý", tier: 2 },
  { id: 192, ru: "по́мнить", en: "to remember", cs: "pamatovat si", tier: 2 },
  { id: 193, ru: "слу́шать", en: "to listen", cs: "poslouchat", tier: 2 },
  { id: 194, ru: "врач", en: "doctor", cs: "lékař", tier: 2 },
  { id: 195, ru: "учи́тель", en: "teacher", cs: "učitel", tier: 2 },
  { id: 196, ru: "лу́чше", en: "better", cs: "lépe", tier: 2 },
  { id: 197, ru: "ху́же", en: "worse", cs: "hůře", tier: 2 },
  { id: 198, ru: "боле́знь", en: "illness", cs: "nemoc", tier: 2 },
  { id: 199, ru: "ме́сяц", en: "month", cs: "měsíc", tier: 2 },
  { id: 200, ru: "неде́ля", en: "week", cs: "týden", tier: 2 },
  { id: 201, ru: "пробле́ма", en: "problem", cs: "problém", tier: 3 },
  { id: 202, ru: "приме́р", en: "example", cs: "příklad", tier: 3 },
  { id: 203, ru: "гру́ппа", en: "group", cs: "skupina", tier: 3 },
  { id: 204, ru: "разви́тие", en: "development", cs: "rozvoj", tier: 3 },
  { id: 205, ru: "результа́т", en: "result", cs: "výsledek", tier: 3 },
  { id: 206, ru: "усло́вие", en: "condition", cs: "podmínka", tier: 3 },
  { id: 207, ru: "наро́д", en: "people, nation", cs: "národ", tier: 3 },
  { id: 208, ru: "о́бласть", en: "region, area", cs: "oblast", tier: 3 },
  { id: 209, ru: "зако́н", en: "law", cs: "zákon", tier: 3 },
  { id: 210, ru: "связь", en: "connection", cs: "spojení", tier: 3 },
  { id: 211, ru: "поря́док", en: "order", cs: "pořádek", tier: 3 },
  { id: 212, ru: "фо́рма", en: "form, shape", cs: "forma", tier: 3 },
  { id: 213, ru: "приро́да", en: "nature", cs: "příroda", tier: 3 },
  { id: 214, ru: "о́бщество", en: "society", cs: "společnost", tier: 3 },
  { id: 215, ru: "движе́ние", en: "movement", cs: "pohyb", tier: 3 },
  { id: 216, ru: "власть", en: "power", cs: "moc", tier: 3 },
  { id: 217, ru: "сре́дство", en: "means, tool", cs: "prostředek", tier: 3 },
  { id: 218, ru: "де́йствие", en: "action", cs: "akce", tier: 3 },
  { id: 219, ru: "ка́чество", en: "quality", cs: "kvalita", tier: 3 },
  { id: 220, ru: "отноше́ние", en: "attitude, relation", cs: "vztah", tier: 3 },
  { id: 221, ru: "внима́ние", en: "attention", cs: "pozornost", tier: 3 },
  { id: 222, ru: "положе́ние", en: "position, situation", cs: "postavení", tier: 3 },
  { id: 223, ru: "возмо́жность", en: "possibility", cs: "možnost", tier: 3 },
  { id: 224, ru: "предме́т", en: "object, subject", cs: "předmět", tier: 3 },
  { id: 225, ru: "цель", en: "goal, aim", cs: "cíl", tier: 3 },
  { id: 226, ru: "во́здух", en: "air", cs: "vzduch", tier: 3 },
  { id: 227, ru: "не́бо", en: "sky", cs: "nebe", tier: 3 },
  { id: 228, ru: "пе́сня", en: "song", cs: "píseň", tier: 3 },
  { id: 229, ru: "пти́ца", en: "bird", cs: "pták", tier: 3 },
  { id: 230, ru: "соба́ка", en: "dog", cs: "pes", tier: 3 },
  { id: 231, ru: "ко́шка", en: "cat", cs: "kočka", tier: 3 },
  { id: 232, ru: "цвето́к", en: "flower", cs: "květina", tier: 3 },
  { id: 233, ru: "де́рево", en: "tree", cs: "strom", tier: 3 },
  { id: 234, ru: "река́", en: "river", cs: "řeka", tier: 3 },
  { id: 235, ru: "мо́ре", en: "sea", cs: "moře", tier: 3 },
  { id: 236, ru: "о́зеро", en: "lake", cs: "jezero", tier: 3 },
  { id: 237, ru: "гора́", en: "mountain", cs: "hora", tier: 3 },
  { id: 238, ru: "лес", en: "forest", cs: "les", tier: 3 },
  { id: 239, ru: "по́ле", en: "field", cs: "pole", tier: 3 },
  { id: 240, ru: "сад", en: "garden", cs: "zahrada", tier: 3 },
  { id: 241, ru: "ку́хня", en: "kitchen", cs: "kuchyně", tier: 3 },
  { id: 242, ru: "спа́льня", en: "bedroom", cs: "ložnice", tier: 3 },
  { id: 243, ru: "ва́нная", en: "bathroom", cs: "koupelna", tier: 3 },
  { id: 244, ru: "магази́н", en: "store, shop", cs: "obchod", tier: 3 },
  { id: 245, ru: "рестора́н", en: "restaurant", cs: "restaurace", tier: 3 },
  { id: 246, ru: "больни́ца", en: "hospital", cs: "nemocnice", tier: 3 },
  { id: 247, ru: "аэропо́рт", en: "airport", cs: "letiště", tier: 3 },
  { id: 248, ru: "вокза́л", en: "train station", cs: "nádraží", tier: 3 },
  { id: 249, ru: "предложи́ть", en: "to offer", cs: "navrhnout", tier: 3 },
  { id: 250, ru: "реши́ть", en: "to decide", cs: "rozhodnout", tier: 3 },
  { id: 251, ru: "предста́вить", en: "to present", cs: "představit", tier: 3 },
  { id: 252, ru: "показа́ть", en: "to show", cs: "ukázat", tier: 3 },
  { id: 253, ru: "созда́ть", en: "to create", cs: "vytvořit", tier: 3 },
  { id: 254, ru: "счита́ть", en: "to consider", cs: "považovat", tier: 3 },
  { id: 255, ru: "тре́бовать", en: "to demand", cs: "požadovat", tier: 3 },
  { id: 256, ru: "продолжа́ть", en: "to continue", cs: "pokračovat", tier: 3 },
  { id: 257, ru: "сле́довать", en: "to follow", cs: "následovat", tier: 3 },
  { id: 258, ru: "забы́ть", en: "to forget", cs: "zapomenout", tier: 3 },
  { id: 259, ru: "появи́ться", en: "to appear", cs: "objevit se", tier: 3 },
  { id: 260, ru: "ждать", en: "to wait", cs: "čekat", tier: 3 },
  { id: 261, ru: "уйти́", en: "to leave", cs: "odejít", tier: 3 },
  { id: 262, ru: "звать", en: "to call", cs: "volat", tier: 3 },
  { id: 263, ru: "иска́ть", en: "to search", cs: "hledat", tier: 3 },
  { id: 264, ru: "ве́рить", en: "to believe", cs: "věřit", tier: 3 },
  { id: 265, ru: "учи́ться", en: "to study", cs: "učit se", tier: 3 },
  { id: 266, ru: "гото́вить", en: "to cook", cs: "vařit", tier: 3 },
  { id: 267, ru: "петь", en: "to sing", cs: "zpívat", tier: 3 },
  { id: 268, ru: "танцева́ть", en: "to dance", cs: "tančit", tier: 3 },
  { id: 269, ru: "рисова́ть", en: "to draw", cs: "kreslit", tier: 3 },
  { id: 270, ru: "пла́вать", en: "to swim", cs: "plavat", tier: 3 },
  { id: 271, ru: "лета́ть", en: "to fly", cs: "létat", tier: 3 },
  { id: 272, ru: "отдыха́ть", en: "to rest", cs: "odpočívat", tier: 3 },
  { id: 273, ru: "гуля́ть", en: "to walk", cs: "procházet se", tier: 3 },
  { id: 274, ru: "встре́тить", en: "to meet", cs: "potkat", tier: 3 },
  { id: 275, ru: "объясни́ть", en: "to explain", cs: "vysvětlit", tier: 3 },
  { id: 276, ru: "ва́жный", en: "important", cs: "důležitý", tier: 3 },
  { id: 277, ru: "ну́жный", en: "necessary", cs: "potřebný", tier: 3 },
  { id: 278, ru: "о́бщий", en: "common, general", cs: "obecný", tier: 3 },
  { id: 279, ru: "по́лный", en: "full, complete", cs: "plný", tier: 3 },
  { id: 280, ru: "просто́й", en: "simple", cs: "jednoduchý", tier: 3 },
  { id: 281, ru: "си́льный", en: "strong", cs: "silný", tier: 3 },
  { id: 282, ru: "возмо́жный", en: "possible", cs: "možný", tier: 3 },
  { id: 283, ru: "изве́стный", en: "famous, known", cs: "známý", tier: 3 },
  { id: 284, ru: "осо́бый", en: "special", cs: "zvláštní", tier: 3 },
  { id: 285, ru: "прекра́сный", en: "beautiful", cs: "nádherný", tier: 3 },
  { id: 286, ru: "тёплый", en: "warm", cs: "teplý", tier: 3 },
  { id: 287, ru: "холо́дный", en: "cold", cs: "studený", tier: 3 },
  { id: 288, ru: "горя́чий", en: "hot", cs: "horký", tier: 3 },
  { id: 289, ru: "све́жий", en: "fresh", cs: "čerstvý", tier: 3 },
  { id: 290, ru: "ти́хий", en: "quiet", cs: "tichý", tier: 3 },
  { id: 291, ru: "гро́мкий", en: "loud", cs: "hlasitý", tier: 3 },
  { id: 292, ru: "лёгкий", en: "light, easy", cs: "lehký", tier: 3 },
  { id: 293, ru: "тяжёлый", en: "heavy, difficult", cs: "těžký", tier: 3 },
  { id: 294, ru: "бы́стрый", en: "fast, quick", cs: "rychlý", tier: 3 },
  { id: 295, ru: "ме́дленный", en: "slow", cs: "pomalý", tier: 3 },
  { id: 296, ru: "обы́чно", en: "usually", cs: "obvykle", tier: 3 },
  { id: 297, ru: "наконе́ц", en: "finally", cs: "konečně", tier: 3 },
  { id: 298, ru: "иногда́", en: "sometimes", cs: "někdy", tier: 3 },
  { id: 299, ru: "снача́ла", en: "at first", cs: "nejdříve", tier: 3 },
  { id: 300, ru: "обяза́тельно", en: "definitely", cs: "určitě", tier: 3 },
  { id: 301, ru: "програ́мма", en: "program", cs: "program", tier: 4 },
  { id: 302, ru: "материа́л", en: "material", cs: "materiál", tier: 4 },
  { id: 303, ru: "произво́дство", en: "production", cs: "výroba", tier: 4 },
  { id: 304, ru: "эконо́мика", en: "economy", cs: "ekonomika", tier: 4 },
  { id: 305, ru: "президе́нт", en: "president", cs: "prezident", tier: 4 },
  { id: 306, ru: "прави́тельство", en: "government", cs: "vláda", tier: 4 },
  { id: 307, ru: "образова́ние", en: "education", cs: "vzdělání", tier: 4 },
  { id: 308, ru: "культу́ра", en: "culture", cs: "kultura", tier: 4 },
  { id: 309, ru: "нау́ка", en: "science", cs: "věda", tier: 4 },
  { id: 310, ru: "иску́сство", en: "art", cs: "umění", tier: 4 },
  { id: 311, ru: "му́зыка", en: "music", cs: "hudba", tier: 4 },
  { id: 312, ru: "спорт", en: "sport", cs: "sport", tier: 4 },
  { id: 313, ru: "здоро́вье", en: "health", cs: "zdraví", tier: 4 },
  { id: 314, ru: "о́пыт", en: "experience", cs: "zkušenost", tier: 4 },
  { id: 315, ru: "интере́с", en: "interest", cs: "zájem", tier: 4 },
  { id: 316, ru: "успе́х", en: "success", cs: "úspěch", tier: 4 },
  { id: 317, ru: "по́мощь", en: "help", cs: "pomoc", tier: 4 },
  { id: 318, ru: "защи́та", en: "protection", cs: "ochrana", tier: 4 },
  { id: 319, ru: "безопа́сность", en: "safety", cs: "bezpečnost", tier: 4 },
  { id: 320, ru: "бу́дущее", en: "future", cs: "budoucnost", tier: 4 },
  { id: 321, ru: "про́шлое", en: "past", cs: "minulost", tier: 4 },
  { id: 322, ru: "мне́ние", en: "opinion", cs: "názor", tier: 4 },
  { id: 323, ru: "оши́бка", en: "mistake", cs: "chyba", tier: 4 },
  { id: 324, ru: "ра́зница", en: "difference", cs: "rozdíl", tier: 4 },
  { id: 325, ru: "свобо́да", en: "freedom", cs: "svoboda", tier: 4 },
  { id: 326, ru: "па́мять", en: "memory", cs: "paměť", tier: 4 },
  { id: 327, ru: "спо́соб", en: "way, method", cs: "způsob", tier: 4 },
  { id: 328, ru: "пра́вило", en: "rule", cs: "pravidlo", tier: 4 },
  { id: 329, ru: "причи́на", en: "reason", cs: "příčina", tier: 4 },
  { id: 330, ru: "вы́бор", en: "choice", cs: "výběr", tier: 4 },
  { id: 331, ru: "реше́ние", en: "decision", cs: "rozhodnutí", tier: 4 },
  { id: 332, ru: "значе́ние", en: "meaning", cs: "význam", tier: 4 },
  { id: 333, ru: "роль", en: "role", cs: "role", tier: 4 },
  { id: 334, ru: "у́ровень", en: "level", cs: "úroveň", tier: 4 },
  { id: 335, ru: "состоя́ние", en: "condition", cs: "stav", tier: 4 },
  { id: 336, ru: "направле́ние", en: "direction", cs: "směr", tier: 4 },
  { id: 337, ru: "ка́рта", en: "map", cs: "mapa", tier: 4 },
  { id: 338, ru: "биле́т", en: "ticket", cs: "lístek", tier: 4 },
  { id: 339, ru: "па́спорт", en: "passport", cs: "pas", tier: 4 },
  { id: 340, ru: "су́мка", en: "bag", cs: "taška", tier: 4 },
  { id: 341, ru: "чемода́н", en: "suitcase", cs: "kufr", tier: 4 },
  { id: 342, ru: "зонт", en: "umbrella", cs: "deštník", tier: 4 },
  { id: 343, ru: "пода́рок", en: "gift", cs: "dárek", tier: 4 },
  { id: 344, ru: "пра́здник", en: "holiday", cs: "svátek", tier: 4 },
  { id: 345, ru: "костю́м", en: "suit", cs: "oblek", tier: 4 },
  { id: 346, ru: "пла́тье", en: "dress", cs: "šaty", tier: 4 },
  { id: 347, ru: "руба́шка", en: "shirt", cs: "košile", tier: 4 },
  { id: 348, ru: "о́бувь", en: "footwear", cs: "obuv", tier: 4 },
  { id: 349, ru: "управля́ть", en: "to manage", cs: "řídit", tier: 4 },
  { id: 350, ru: "отказа́ться", en: "to refuse", cs: "odmítnout", tier: 4 },
  { id: 351, ru: "согласи́ться", en: "to agree", cs: "souhlasit", tier: 4 },
  { id: 352, ru: "зави́сеть", en: "to depend", cs: "záviset", tier: 4 },
  { id: 353, ru: "относи́ться", en: "to relate to", cs: "vztahovat se", tier: 4 },
  { id: 354, ru: "происходи́ть", en: "to happen", cs: "dít se", tier: 4 },
  { id: 355, ru: "существова́ть", en: "to exist", cs: "existovat", tier: 4 },
  { id: 356, ru: "по́льзоваться", en: "to use", cs: "používat", tier: 4 },
  { id: 357, ru: "занима́ться", en: "to be engaged in", cs: "zabývat se", tier: 4 },
  { id: 358, ru: "доба́вить", en: "to add", cs: "přidat", tier: 4 },
  { id: 359, ru: "меня́ть", en: "to change", cs: "měnit", tier: 4 },
  { id: 360, ru: "прове́рить", en: "to check", cs: "zkontrolovat", tier: 4 },
  { id: 361, ru: "вы́брать", en: "to choose", cs: "vybrat", tier: 4 },
  { id: 362, ru: "попроси́ть", en: "to ask, request", cs: "poprosit", tier: 4 },
  { id: 363, ru: "заказа́ть", en: "to order", cs: "objednat", tier: 4 },
  { id: 364, ru: "сове́товать", en: "to advise", cs: "radit", tier: 4 },
  { id: 365, ru: "жа́ловаться", en: "to complain", cs: "stěžovat si", tier: 4 },
  { id: 366, ru: "мечта́ть", en: "to dream", cs: "snít", tier: 4 },
  { id: 367, ru: "волнова́ться", en: "to worry", cs: "znepokojovat se", tier: 4 },
  { id: 368, ru: "привы́кнуть", en: "to get used to", cs: "zvyknout si", tier: 4 },
  { id: 369, ru: "путеше́ствовать", en: "to travel", cs: "cestovat", tier: 4 },
  { id: 370, ru: "фотографи́ровать", en: "to photograph", cs: "fotografovat", tier: 4 },
  { id: 371, ru: "совреме́нный", en: "modern", cs: "moderní", tier: 4 },
  { id: 372, ru: "ме́стный", en: "local", cs: "místní", tier: 4 },
  { id: 373, ru: "основно́й", en: "main, basic", cs: "základní", tier: 4 },
  { id: 374, ru: "разли́чный", en: "various", cs: "různý", tier: 4 },
  { id: 375, ru: "фина́нсовый", en: "financial", cs: "finanční", tier: 4 },
  { id: 376, ru: "полити́ческий", en: "political", cs: "politický", tier: 4 },
  { id: 377, ru: "нау́чный", en: "scientific", cs: "vědecký", tier: 4 },
  { id: 378, ru: "культу́рный", en: "cultural", cs: "kulturní", tier: 4 },
  { id: 379, ru: "социа́льный", en: "social", cs: "sociální", tier: 4 },
  { id: 380, ru: "удо́бный", en: "comfortable", cs: "pohodlný", tier: 4 },
  { id: 381, ru: "опа́сный", en: "dangerous", cs: "nebezpečný", tier: 4 },
  { id: 382, ru: "безопа́сный", en: "safe", cs: "bezpečný", tier: 4 },
  { id: 383, ru: "счастли́вый", en: "happy", cs: "šťastný", tier: 4 },
  { id: 384, ru: "гру́стный", en: "sad", cs: "smutný", tier: 4 },
  { id: 385, ru: "злой", en: "angry", cs: "zlý", tier: 4 },
  { id: 386, ru: "ве́жливый", en: "polite", cs: "zdvořilý", tier: 4 },
  { id: 387, ru: "лени́вый", en: "lazy", cs: "líný", tier: 4 },
  { id: 388, ru: "действи́тельно", en: "really", cs: "opravdu", tier: 4 },
  { id: 389, ru: "возмо́жно", en: "possibly", cs: "možná", tier: 4 },
  { id: 390, ru: "поэ́тому", en: "therefore", cs: "proto", tier: 4 },
  { id: 391, ru: "безусло́вно", en: "absolutely", cs: "bezpochyby", tier: 4 },
  { id: 392, ru: "постоя́нно", en: "constantly", cs: "neustále", tier: 4 },
  { id: 393, ru: "нало́г", en: "tax", cs: "daň", tier: 4 },
  { id: 394, ru: "населе́ние", en: "population", cs: "obyvatelstvo", tier: 4 },
  { id: 395, ru: "собы́тие", en: "event", cs: "událost", tier: 4 },
  { id: 396, ru: "пе́нсия", en: "pension", cs: "důchod", tier: 4 },
  { id: 397, ru: "до́лжность", en: "position, post", cs: "funkce", tier: 4 },
  { id: 398, ru: "приме́рно", en: "approximately", cs: "přibližně", tier: 4 },
  { id: 399, ru: "поведе́ние", en: "behavior", cs: "chování", tier: 4 },
  { id: 400, ru: "во́зраст", en: "age", cs: "věk", tier: 4 },
  { id: 401, ru: "удово́льствие", en: "pleasure", cs: "potěšení", tier: 5 },
  { id: 402, ru: "впечатле́ние", en: "impression", cs: "dojem", tier: 5 },
  { id: 403, ru: "приключе́ние", en: "adventure", cs: "dobrodružství", tier: 5 },
  { id: 404, ru: "настрое́ние", en: "mood", cs: "nálada", tier: 5 },
  { id: 405, ru: "терпе́ние", en: "patience", cs: "trpělivost", tier: 5 },
  { id: 406, ru: "уваже́ние", en: "respect", cs: "úcta", tier: 5 },
  { id: 407, ru: "дове́рие", en: "trust", cs: "důvěra", tier: 5 },
  { id: 408, ru: "со́весть", en: "conscience", cs: "svědomí", tier: 5 },
  { id: 409, ru: "справедли́вость", en: "justice", cs: "spravedlnost", tier: 5 },
  { id: 410, ru: "му́дрость", en: "wisdom", cs: "moudrost", tier: 5 },
  { id: 411, ru: "ве́жливость", en: "politeness", cs: "zdvořilost", tier: 5 },
  { id: 412, ru: "го́рдость", en: "pride", cs: "hrdost", tier: 5 },
  { id: 413, ru: "че́стность", en: "honesty", cs: "poctivost", tier: 5 },
  { id: 414, ru: "отве́тственность", en: "responsibility", cs: "odpovědnost", tier: 5 },
  { id: 415, ru: "сто́имость", en: "cost", cs: "cena", tier: 5 },
  { id: 416, ru: "расхо́д", en: "expense", cs: "výdaj", tier: 5 },
  { id: 417, ru: "дохо́д", en: "income", cs: "příjem", tier: 5 },
  { id: 418, ru: "зарпла́та", en: "salary", cs: "plat", tier: 5 },
  { id: 419, ru: "ски́дка", en: "discount", cs: "sleva", tier: 5 },
  { id: 420, ru: "квита́нция", en: "receipt", cs: "stvrzenka", tier: 5 },
  { id: 421, ru: "чек", en: "check", cs: "účtenka", tier: 5 },
  { id: 422, ru: "догово́р", en: "contract", cs: "smlouva", tier: 5 },
  { id: 423, ru: "заявле́ние", en: "application", cs: "žádost", tier: 5 },
  { id: 424, ru: "расписа́ние", en: "schedule", cs: "rozvrh", tier: 5 },
  { id: 425, ru: "объявле́ние", en: "announcement", cs: "oznámení", tier: 5 },
  { id: 426, ru: "достопримеча́тельность", en: "landmark", cs: "památka", tier: 5 },
  { id: 427, ru: "ры́нок", en: "market", cs: "trh", tier: 5 },
  { id: 428, ru: "апте́ка", en: "pharmacy", cs: "lékárna", tier: 5 },
  { id: 429, ru: "библиоте́ка", en: "library", cs: "knihovna", tier: 5 },
  { id: 430, ru: "мастерска́я", en: "workshop", cs: "dílna", tier: 5 },
  { id: 431, ru: "парикма́херская", en: "hair salon", cs: "kadeřnictví", tier: 5 },
  { id: 432, ru: "по́чта", en: "post office", cs: "pošta", tier: 5 },
  { id: 433, ru: "поли́ция", en: "police", cs: "policie", tier: 5 },
  { id: 434, ru: "посо́льство", en: "embassy", cs: "ambasáda", tier: 5 },
  { id: 435, ru: "грани́ца", en: "border", cs: "hranice", tier: 5 },
  { id: 436, ru: "ви́за", en: "visa", cs: "vízum", tier: 5 },
  { id: 437, ru: "тамо́жня", en: "customs", cs: "celnice", tier: 5 },
  { id: 438, ru: "за́втрак", en: "breakfast", cs: "snídaně", tier: 5 },
  { id: 439, ru: "обе́д", en: "lunch", cs: "oběd", tier: 5 },
  { id: 440, ru: "у́жин", en: "dinner", cs: "večeře", tier: 5 },
  { id: 441, ru: "блю́до", en: "dish", cs: "jídlo", tier: 5 },
  { id: 442, ru: "суп", en: "soup", cs: "polévka", tier: 5 },
  { id: 443, ru: "ка́ша", en: "porridge", cs: "kaše", tier: 5 },
  { id: 444, ru: "мя́со", en: "meat", cs: "maso", tier: 5 },
  { id: 445, ru: "ры́ба", en: "fish", cs: "ryba", tier: 5 },
  { id: 446, ru: "о́вощи", en: "vegetables", cs: "zelenina", tier: 5 },
  { id: 447, ru: "фрукт", en: "fruit", cs: "ovoce", tier: 5 },
  { id: 448, ru: "сомнева́ться", en: "to doubt", cs: "pochybovat", tier: 5 },
  { id: 449, ru: "извини́ться", en: "to apologize", cs: "omluvit se", tier: 5 },
  { id: 450, ru: "поздра́вить", en: "to congratulate", cs: "blahopřát", tier: 5 },
  { id: 451, ru: "благодари́ть", en: "to thank", cs: "děkovat", tier: 5 },
  { id: 452, ru: "обеща́ть", en: "to promise", cs: "slíbit", tier: 5 },
  { id: 453, ru: "удиви́ться", en: "to be surprised", cs: "divit se", tier: 5 },
  { id: 454, ru: "обнару́жить", en: "to discover", cs: "objevit", tier: 5 },
  { id: 455, ru: "восхища́ться", en: "to admire", cs: "obdivovat", tier: 5 },
  { id: 456, ru: "преодоле́ть", en: "to overcome", cs: "překonat", tier: 5 },
  { id: 457, ru: "отмени́ть", en: "to cancel", cs: "zrušit", tier: 5 },
  { id: 458, ru: "подтверди́ть", en: "to confirm", cs: "potvrdit", tier: 5 },
  { id: 459, ru: "разреши́ть", en: "to allow", cs: "povolit", tier: 5 },
  { id: 460, ru: "запрети́ть", en: "to forbid", cs: "zakázat", tier: 5 },
  { id: 461, ru: "предупреди́ть", en: "to warn", cs: "varovat", tier: 5 },
  { id: 462, ru: "избежа́ть", en: "to avoid", cs: "vyhnout se", tier: 5 },
  { id: 463, ru: "опозда́ть", en: "to be late", cs: "přijít pozdě", tier: 5 },
  { id: 464, ru: "спеши́ть", en: "to hurry", cs: "spěchat", tier: 5 },
  { id: 465, ru: "торопи́ться", en: "to rush", cs: "pospíchat", tier: 5 },
  { id: 466, ru: "отложи́ть", en: "to postpone", cs: "odložit", tier: 5 },
  { id: 467, ru: "перенести́", en: "to reschedule", cs: "přeložit", tier: 5 },
  { id: 468, ru: "отве́тственный", en: "responsible", cs: "odpovědný", tier: 5 },
  { id: 469, ru: "справедли́вый", en: "fair", cs: "spravedlivý", tier: 5 },
  { id: 470, ru: "че́стный", en: "honest", cs: "poctivý", tier: 5 },
  { id: 471, ru: "скро́мный", en: "modest", cs: "skromný", tier: 5 },
  { id: 472, ru: "ще́дрый", en: "generous", cs: "štědrý", tier: 5 },
  { id: 473, ru: "жа́дный", en: "greedy", cs: "chamtivý", tier: 5 },
  { id: 474, ru: "терпели́вый", en: "patient", cs: "trpělivý", tier: 5 },
  { id: 475, ru: "трудолюби́вый", en: "hardworking", cs: "pracovitý", tier: 5 },
  { id: 476, ru: "любопы́тный", en: "curious", cs: "zvědavý", tier: 5 },
  { id: 477, ru: "серьёзный", en: "serious", cs: "vážný", tier: 5 },
  { id: 478, ru: "смешно́й", en: "funny", cs: "legrační", tier: 5 },
  { id: 479, ru: "стра́нный", en: "strange", cs: "zvláštní", tier: 5 },
  { id: 480, ru: "обы́чный", en: "ordinary", cs: "obvyklý", tier: 5 },
  { id: 481, ru: "необы́чный", en: "unusual", cs: "neobvyklý", tier: 5 },
  { id: 482, ru: "похо́жий", en: "similar", cs: "podobný", tier: 5 },
  { id: 483, ru: "отли́чный", en: "excellent", cs: "výborný", tier: 5 },
  { id: 484, ru: "ужа́сный", en: "terrible", cs: "hrozný", tier: 5 },
  { id: 485, ru: "к сожале́нию", en: "unfortunately", cs: "bohužel", tier: 5 },
  { id: 486, ru: "по-мо́ему", en: "in my opinion", cs: "podle mě", tier: 5 },
  { id: 487, ru: "по-ва́шему", en: "in your opinion", cs: "podle vás", tier: 5 },
  { id: 488, ru: "по кра́йней ме́ре", en: "at least", cs: "alespoň", tier: 5 },
  { id: 489, ru: "в о́бщем", en: "in general", cs: "celkově", tier: 5 },
  { id: 490, ru: "на са́мом де́ле", en: "in fact", cs: "ve skutečnosti", tier: 5 },
  { id: 491, ru: "коне́чно", en: "of course", cs: "samozřejmě", tier: 5 },
  { id: 492, ru: "напи́ток", en: "beverage", cs: "nápoj", tier: 5 },
  { id: 493, ru: "десе́рт", en: "dessert", cs: "dezert", tier: 5 },
  { id: 494, ru: "реце́пт", en: "recipe", cs: "recept", tier: 5 },
  { id: 495, ru: "по́рция", en: "portion", cs: "porce", tier: 5 },
  { id: 496, ru: "сала́т", en: "salad", cs: "salát", tier: 5 },
  { id: 497, ru: "обяза́тельный", en: "obligatory", cs: "povinný", tier: 5 },
  { id: 498, ru: "впро́чем", en: "however", cs: "nicméně", tier: 5 },
  { id: 499, ru: "тем не ме́нее", en: "nevertheless", cs: "přesto", tier: 5 },
  { id: 500, ru: "пожа́луй", en: "perhaps", cs: "snad", tier: 5 }
];
